config/routes.rb
# == Route Map
#
#                     Prefix Verb   URI Pattern                           Controller#Action
#                      login GET    /login(.:format)                      sessions#new
#                            POST   /login(.:format)                      sessions#create
#                            DELETE /login(.:format)                      sessions#destroy
#                       root GET    /                                     recipes#home
#             recipes_search GET    /recipes/search(.:format)             recipes#search_recipes
# recipes_search_ingredients GET    /recipes/search_ingredients(.:format) recipes#multiple_ingredients_search
#             search_results GET    /recipes/search_results(.:format)     recipes#search_results
#                 edit_users GET    /users/edit(.:format)                 users#edit
#                      users GET    /users(.:format)                      users#index
#                            POST   /users(.:format)                      users#create
#                   new_user GET    /users/new(.:format)                  users#new
#                       user GET    /users/:id(.:format)                  users#show
#                            PATCH  /users/:id(.:format)                  users#update
#                            PUT    /users/:id(.:format)                  users#update
#                            DELETE /users/:id(.:format)                  users#destroy
#

Rails.application.routes.draw do

  get '/login' => 'sessions#new' 
  post '/login' => 'sessions#create'
  delete '/login' => 'sessions#destroy'

root :to => 'recipes#home'

get '/recipes/search' => 'recipes#search_recipes'
get '/recipes/search_ingredients' => 'recipes#multiple_ingredients_search'
get '/recipes/search_results' => 'recipes#search_results', :as => "search_results"

resources :users, :except => [:edit] do
    collection do
      get '/edit' => 'users#edit'
    end
  end

post 'users/favorite' => 'users#favorite'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Whatscooking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--  Display Feature try out  -->
<div class="brand">What's Cooking</div>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">
            <img class="img-responsive" alt="Brand" src="http://cdn.scrapbook.com/products/cache/SBC_fab-dc47021_0.jpg"> 
          </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"> <%= link_to "Home", root_path %> </li>
            <!-- If Admin user , Display List of users -->
            <% if @current_user.present? && @current_user.admin? %>
                  <li> <%=link_to('Show Users' ,users_path) %> </li>
            <% end %>

            <!-- If the user had logged on  -->
            <% if  @current_user.present? %>
                <li> <%= link_to('Edit Profile' ,edit_users_path) %> </li>
                <li> <%= link_to("log out #{@current_user.full_name}",login_path, :method => :delete, :confirm => 'Are you sure?') %></li>
                <li> <%= link_to('Favorites' ,user_path(@current_user)) %></li>

              <!-- if the user has not logged on   -->
             <% else  %>
                 <li> <%= link_to('Sign Up' , new_user_path) %></li>
                 <li> <%= link_to('Log in', login_path) %></li>
             <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
              <div class="form-group">
                  <%= form_tag("/recipes/search" ,method: "get", class: "navbar-form navbar-right") do %>
                      <%= text_field_tag(:recipe_name ,nil , placeholder: "Search for recipe...", class: "form-control") %>
                      <%= submit_tag("Search" ,class: "btn btn-primary" ) %> 
                  <% end %>
              </div>
              </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

<div class="row">
  <div class="col-lg-3 col-md-3 ">
    <div id="wrapper">
     <!-- Sidebar Menu Items  -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <a href="#">
              <img class="img-responsive" alt="Brand" src="http://cdn.scrapbook.com/products/cache/SBC_fab-dc47021_0.jpg"> 
            </a>
          </li>   
         <!-- Search based on the Ingredient list  -->
          <%= form_tag("/recipes/search_ingredients", method: "get" ,class: "form-horizontal") do %>

              <h3 class="form-signin-heading"> Search by Ingredients</h3>
              
              <div class="form-group">
                <%= text_field_tag(:ingredient1, nil ,placeholder: "Ingredient 1") %>
              </div>

              <div class="form-group">
                <%= text_field_tag(:ingredient2, nil ,placeholder: "Ingredient 2") %>
              </div>

              <div class="form-group">
                <%= text_field_tag(:ingredient3, nil ,placeholder: "Ingredient 3") %>
              </div>

              <div class="form-group">
              <%= select_tag(:diet, options_for_select([
                ['No-sugar'], 
                ['Vegetarian'],
                ['Vegan'],
                ['Paleo'],
                ['Gluten-free'],
                ['Wheat-free'],
                ['Paleo'],
                ['Egg-Free'],
                ['Tree-Nut-Free'],
                ['Alcohol-free'],
                ['No oil added'],
                ['Peanut-Free'],
                ['Shellfish-Free'],
                ['Fish-Free'],
                ['Soy-Free'],
                ['Dairy-Free'],
                ]), :include_blank => true
            )%>
             </div>
               
              <%= submit_tag("Search" ,class: "btn btn-primary") %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="col-lg-7 col-md-7 ">
      <!-- Page Content -->
        <div id="page-content-wrapper">
          <div class="container-fluid">
              <div class="row">
                 <div class="col-lg-12">
                    <p> Your food forage ends here </p>
                        <%= yield %>
                  </div>
               </div>
          </div>
        </div>
        <!-- /#page-content-wrapper -->
      </div>
    </div>



<!-- End of Try out  -->
     

</body>
</html>


<!-- 
http://www.foodwise.com.au/wp-content/uploads/2012/10/ChoppingBoard2.gif
http://th05.deviantart.net/fs11/PRE/i/2006/255/f/7/Chopping_Board___stock_by_stillwater__stock.jpg

body {
 
   
  background-image: url("http://www.shutterstock.com/blog/wp-content/uploads/sites/5/2013/05/shutterstock_83564761.jpg");
  background-position: cover;
  background-repeat: no-repeat;
}
 -->